# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- '*'

resources:
- repo: self


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'mssql-2019-windows-2022'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/windows/mssql-server-windows-developer/dockerfile'
        tags: 'nano'
